### Exercise_Week08_Python
* import necessary libraries in the box below

In [12]:
import numpy as np
import pandas as pd

### Question 01
Create a NumPy array from [-60,-59,...,-1,0,1,2,3,...,60].

* Replace all odd numbers with -1

In [3]:


array_01 = np.arange(-60, 61)
array_01 = np.where(array_01 % 2 == 1, -1, array_01)
print(array_01)

[-60  -1 -58  -1 -56  -1 -54  -1 -52  -1 -50  -1 -48  -1 -46  -1 -44  -1
 -42  -1 -40  -1 -38  -1 -36  -1 -34  -1 -32  -1 -30  -1 -28  -1 -26  -1
 -24  -1 -22  -1 -20  -1 -18  -1 -16  -1 -14  -1 -12  -1 -10  -1  -8  -1
  -6  -1  -4  -1  -2  -1   0  -1   2  -1   4  -1   6  -1   8  -1  10  -1
  12  -1  14  -1  16  -1  18  -1  20  -1  22  -1  24  -1  26  -1  28  -1
  30  -1  32  -1  34  -1  36  -1  38  -1  40  -1  42  -1  44  -1  46  -1
  48  -1  50  -1  52  -1  54  -1  56  -1  58  -1  60]


### Question 02
With np.where, find the positions of:

* Find Elements in x where its value is more than its corresponding element in y.
* Elements in x where its value is equals to its corresponding element in y.

In [3]:
x = np.array([21, 64, 86, 22, 74, 55, 81, 79, 90, 89]) 
y = np.array([21, 7, 3, 45, 74, 29, 55, 4, 37, 18])
pos_more = np.where(x > y)
pos_equal = np.where(x == y)
print(pos_more)   
print(pos_equal)  

(array([1, 2, 5, 6, 7, 8, 9]),)
(array([0, 4]),)


### Question 03

Create a random 7×24 matrix representing hourly temperatures for one week.

(7 days, 24 Hour)

* Find the hour with the highest average temperature.
* Find the day with the highest average temperature.
* Compute the difference between max and min temperature.

In [4]:
array_03 = np.random.uniform(0, 20, size=(7, 24))
hour_means = array_03.mean(axis=0)   
best_hour = np.argmax(hour_means)    
best_hour_avg = hour_means[best_hour]
day_means = array_03.mean(axis=1)    
best_day = np.argmax(day_means)      
best_day_avg = day_means[best_day]
temp_diff = array_03.max() - array_03.min()

print("ساعت با بالاترین میانگین:", best_hour, "میانگین:", best_hour_avg)
print("روز با بالاترین میانگین:", best_day, "میانگین:", best_day_avg)
print("اختلاف max و min:", temp_diff)


ساعت با بالاترین میانگین: 9 میانگین: 14.05957130324701
روز با بالاترین میانگین: 2 میانگین: 12.443658973720664
اختلاف max و min: 19.866466013227864


### Question 04
Create a 30×5 matrix (30 students, 5 courses).

* Compute each student's average.
* Compute each course average.
* Identify students who scored above 15 in at least 3 courses.
* Find the hardest course (with the loest scores)

In [6]:
array_04 = np.random.randint(0, 21, size=(30, 5))
student_avg = array_04.mean(axis=1)
course_avg = array_04.mean(axis=0)
above_15_count = (array_04 > 15).sum(axis=1)
good_students_indices = np.where(above_15_count >= 3)
hardest_course_index = np.argmin(course_avg)
print("Students with >=3 scores above 15 (indices):\n", good_students_indices)
print("Hardest course index:", hardest_course_index)

Students with >=3 scores above 15 (indices):
 (array([0, 6, 7]),)
Hardest course index: 1


### Question 05

Generate two 1D arrays for 12 months:

Income array (values between 5000–15000)

Expenses array (values between 3000–12000)

* Compute monthly profit.
* Find the most profitable month.
* Identify loss months (profit < 0).

In [ ]:
income_array = np.random.randint(5000, 15001, size=12)
expenses_array = np.random.randint(3000, 12001, size=12)
monthly_profit = income_array - expenses_array
most_profitable_month = monthly_profit.max()
most_profitable_months = np.where(monthly_profit == most_profitable_month)
print(most_profitable_months)
loss_months=np.where(monthly_profit<0)
print(loss_months)

(array([8]),)
(array([4]),)


### Question 06

Create a Series with 30 different product names as indexes

and enter random numbers (sales) as values.

* Find best-selling product.
* Compute percentage share of each product.
* Remove products below average sales.

In [26]:
sales_series =  np.random.randint(10, 500, size=30)
indexes = []                     
for i in range(30):               
    index_i = "Product_" + str(i+1) 
    indexes.append(index_i) 
s = pd.Series(sales_series, index=indexes, name="Sales")   
best_product=s.idxmax()
print("best product:",best_product)
share_percent = (s / s.sum()) * 100
avg_sales = s.mean()
s_above_avg = s[s >= avg_sales]

best product: Product_10


### Question 07

Create a Series of 100 student with GPA (values between 8 and 20).

Change index of the series with student names.

* Find top 20% Students and print their names.
* Label students above 17 as "Excellent".

In [32]:
gpa = pd.Series(np.random.uniform(8, 20, 100))
student_names = []                     
for i in range(100):               
    index_i = "student_" + str(i+1) 
    student_names.append(index_i) 
gpa.index = student_names   
top_students=gpa.nlargest(20)
print(top_students.index)
labels = np.where(gpa > 17, "Excellent", "Normal")

Index(['student_86', 'student_90', 'student_82', 'student_71', 'student_27',
       'student_39', 'student_34', 'student_6', 'student_92', 'student_31',
       'student_57', 'student_38', 'student_84', 'student_65', 'student_21',
       'student_78', 'student_13', 'student_100', 'student_19', 'student_99'],
      dtype='str')


### Question 08

Create a Series of 50 people birthday year (1925 to 2025)

and set indexes with their gender (random Female/Male).

then, separate these 50 pople into 6 different series based on their generation:

* Alpha: Born 2013–2025.
* Z: Born 1997–2012 (Ages 14–29).
* Millennials: Born 1981–1996 (Ages 30–45).
* X: Born 1965–1980 (Ages 46–61).
* Baby Boomers: Born 1946–1964 (Ages 62–80).
* Silent: Born 1925–1945 (Ages 81–101). 

Finally, print number of Female and Male popele in each generation.

In [33]:
np.random.seed(42)
years = np.random.randint(1925, 2026, size=50)
genders = np.random.choice(["Female", "Male"], size=50)
birth_series = pd.Series(years, index=genders)
alpha = birth_series[(birth_series >= 2013) & (birth_series <= 2025)]
gen_z = birth_series[(birth_series >= 1997) & (birth_series <= 2012)]
millennials = birth_series[(birth_series >= 1981) & (birth_series <= 1996)]
gen_x = birth_series[(birth_series >= 1965) & (birth_series <= 1980)]
boomers = birth_series[(birth_series >= 1946) & (birth_series <= 1964)]
silent = birth_series[(birth_series >= 1925) & (birth_series <= 1945)]
print("Alpha:\n", alpha.index.value_counts())
print("Z:\n", gen_z.index.value_counts())
print("Millennials:\n", millennials.index.value_counts())
print("X:\n", gen_x.index.value_counts())
print("Baby Boomers:\n", boomers.index.value_counts())
print("Silent:\n", silent.index.value_counts())


Alpha:
 Male      5
Female    1
Name: count, dtype: int64
Z:
 Male      6
Female    3
Name: count, dtype: int64
Millennials:
 Male      9
Female    2
Name: count, dtype: int64
X:
 Male      7
Female    1
Name: count, dtype: int64
Baby Boomers:
 Male      4
Female    2
Name: count, dtype: int64
Silent:
 Male      5
Female    5
Name: count, dtype: int64
